import React from 'react';
import { FileJson, FileSpreadsheet, FileText, Download } from 'lucide-react';

const ExportPanel = ({ data }) => {
  const triggerDownload = (content, filename, mimeType) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportGeoJSON = () => {
    const content = JSON.stringify(data.geojson, null, 2);
    triggerDownload(content, 'disasterscout-damage-map.geojson', 'application/json');
  };

  const exportCSV = () => {
    const headers = ['Sector', 'Damage Type', 'Priority', 'Severity', 'Confidence', 'Lat', 'Lng', 'Area Km2'];
    const rows = data.locations.map(loc => [
      loc.sectorName,
      loc.damageType,
      loc.priority,
      loc.severity,
      loc.confidence,
      loc.coords.lat,
      loc.coords.lng,
      loc.areaKm2
    ]);
    const content = [headers, ...rows].map(row => row.join(',')).join('\n');
    triggerDownload(content, 'disasterscout-locations.csv', 'text/csv');
  };

  const exportReport = () => {
    const stats = data.stats;
    const event = data.event;
    const content = `================================================
DISASTERSCOUT SITUATION REPORT
================================================
Event:     ${event.name}
Location:  ${event.location}
Generated: ${new Date().toLocaleString()}
Satellite: ${event.satelliteSource}
------------------------------------------------
DAMAGE SUMMARY
Buildings Damaged:  ${stats.buildingsDamaged}
Roads Blocked:      ${stats.roadsBlocked}
Area Analyzed:      ${stats.totalAreaAnalyzedKm2} km²
Confidence Score:   ${(stats.confidenceScore * 100).toFixed(0)}%
------------------------------------------------
SEVERITY BREAKDOWN
Critical: ${stats.severeCases} cases
Moderate: ${stats.moderateCases} cases
Minor:    ${stats.minorCases} cases
------------------------------------------------
AI SITUATION REPORT
[This section will be generated by Claude API in Phase 3]
================================================`;
    triggerDownload(content, 'disasterscout-report.txt', 'text/plain');
  };

  const cards = [
    {
      id: 'geojson',
      Icon: FileJson,
      title: 'Damage Map (GeoJSON)',
      description: 'Compatible with QGIS, Google Earth, and ArcGIS. Contains all damage polygons with severity scores and GPS coordinates.',
      buttonText: 'Download GeoJSON',
      onClick: exportGeoJSON
    },
    {
      id: 'csv',
      Icon: FileSpreadsheet,
      title: 'Affected Locations (CSV)',
      description: 'Sortable spreadsheet of all damage zones with GPS coordinates for field team distribution.',
      buttonText: 'Download CSV',
      onClick: exportCSV
    },
    {
      id: 'report',
      Icon: FileText,
      title: 'Situation Report (TXT)',
      description: 'AI-generated natural language report. Full Claude API integration coming in Phase 3.',
      buttonText: 'Download Report',
      onClick: exportReport
    }
  ];

  return (
    <div className="p-8 max-w-[800px] mx-auto space-y-4">
      <h2 className="text-xl font-bold mb-6 text-[var(--text-primary)]">Data Export</h2>
      {cards.map((card) => (
        <div key={card.id} className="bg-[var(--card-bg)] border border-[var(--sidebar-border)] rounded-xl p-6 flex items-start gap-6 transition-all hover:border-[var(--accent)]/50 group">
          <div className="p-4 rounded-lg bg-[var(--sidebar-bg)] text-[var(--accent)] group-hover:scale-110 transition-transform">
            <card.Icon size={32} />
          </div>
          <div className="flex-1 space-y-2">
            <h3 className="text-lg font-bold text-[var(--text-primary)]">{card.title}</h3>
            <p className="text-sm text-[var(--text-secondary)] leading-relaxed">{card.description}</p>
            <button
              onClick={card.onClick}
              className="mt-4 inline-flex items-center gap-2 bg-[var(--accent)] hover:bg-[var(--accent)]/80 text-white text-sm font-bold px-5 py-2.5 rounded-lg transition-colors shadow-lg"
            >
              <Download size={16} />
              {card.buttonText}
            </button>
          </div>
        </div>
      ))}
    </div>
  );
};

export default ExportPanel;
