import React, { useState, useEffect } from 'react';
import { Brain } from 'lucide-react';

const SituationReport = ({ report, loading, onRegenerate }) => {
  const [displayed, setDisplayed] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [copied, setCopied] = useState(false);
  const [isRegenerating, setIsRegenerating] = useState(false);

  useEffect(() => {
    if (!report) return;
    setDisplayed('');
    setIsTyping(true);
    let i = 0;
    const interval = setInterval(() => {
      setDisplayed(report.slice(0, i));
      i++;
      if (i > report.length) {
        clearInterval(interval);
        setIsTyping(false);
      }
    }, 8); // 8ms per character — fast but visible
    return () => clearInterval(interval);
  }, [report]);

  const handleCopy = () => {
    if (!report) return;
    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRegenerate = async () => {
    if (onRegenerate) {
      setIsRegenerating(true);
      try {
        await onRegenerate();
      } finally {
        setIsRegenerating(false);
      }
    }
  };

  if (loading && !report) {
    return (
      <div className="bg-[var(--card-bg)] rounded-lg p-4 border border-[var(--sidebar-border)] mt-4">
        <div className="flex items-center gap-2 mb-4">
          <Brain size={14} className="text-[var(--text-secondary)]" />
          <h3 className="text-[12px] uppercase text-[var(--text-secondary)] font-bold">AI Situation Report</h3>
        </div>
        <div className="animate-pulse space-y-3">
          <div className="h-2 bg-[var(--sidebar-border)] rounded w-full"></div>
          <div className="h-2 bg-[var(--sidebar-border)] rounded w-5/6"></div>
          <div className="h-2 bg-[var(--sidebar-border)] rounded w-4/6"></div>
          <div className="h-2 bg-[var(--sidebar-border)] rounded w-full"></div>
        </div>
        <p className="text-[11px] text-[var(--text-secondary)] mt-4 text-center">Generating situation report...</p>
      </div>
    );
  }

  if (!report && !loading) {
    return (
      <div className="bg-[var(--card-bg)] rounded-lg p-4 border border-[var(--sidebar-border)] mt-4 text-center">
        <Brain size={24} className="text-[var(--text-secondary)] mx-auto mb-2 opacity-50" />
        <p className="text-[12px] text-[var(--text-secondary)]">Run an analysis to generate a situation report</p>
      </div>
    );
  }

  const paragraphs = displayed.split('\n\n').filter(p => p.trim() !== '');

  return (
    <div className="bg-[var(--card-bg)] rounded-lg p-4 border border-[var(--sidebar-border)] mt-4 flex flex-col">
      <div className="flex justify-between items-center mb-4">
        <div className="flex items-center gap-2">
          <Brain size={14} className="text-[var(--text-secondary)]" />
          <h3 className="text-[12px] uppercase text-[var(--text-secondary)] font-bold">AI Situation Report</h3>
        </div>
        {report && (
          <button 
            onClick={handleRegenerate} 
            disabled={isRegenerating}
            className="text-[11px] text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors flex items-center gap-1"
          >
            {isRegenerating ? (
              <>
                <div className="w-3 h-3 border-2 border-[var(--sidebar-border)] border-t-[var(--accent)] rounded-full animate-spin"></div>
                Regenerating
              </>
            ) : (
              'Regenerate'
            )}
          </button>
        )}
      </div>
      
      <div className="flex-1 mb-4 select-text">
        {paragraphs.map((p, idx) => (
          <div key={idx} className="report-paragraph">
            {p}
            {isTyping && idx === paragraphs.length - 1 && (
              <span style={{ animation: 'blink 1s infinite', color: 'var(--accent)' }}>|</span>
            )}
          </div>
        ))}
      </div>

      <div className="flex justify-between items-center mt-2 border-t border-[var(--sidebar-border)] pt-3">
        <div className="flex items-center gap-1 text-[11px] text-[var(--text-secondary)]">
          <Brain size={11} className="opacity-70" />
          Generated by Claude · Based on AI damage assessment
        </div>
        <button 
          onClick={handleCopy}
          className="text-[11px] bg-[var(--sidebar-bg)] border border-[var(--sidebar-border)] px-2 py-1 rounded hover:border-[var(--accent)] text-[var(--text-primary)] transition-colors"
        >
          {copied ? 'Copied!' : 'Copy Report'}
        </button>
      </div>
    </div>
  );
};

export default SituationReport;
